version: '3'

services:
  api-todo:
    image: api-todo
    container_name: api-todo
    build:
      context: ./mvp3-api-todo
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5000

  api-bridge:
    image: api-bridge
    container_name: api-bridge
    build:
      context: ./mvp3-api-bridge
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5001
      - WEATHER_API_KEY=SET_YOUR_API_KEY_HERE
      - WEATHER_API_URL=http://api.openweathermap.org/data/2.5
      - WEATHER_API_UNITS=metric
      - WEATHER_API_LANG=pt_br
      - WEATHER_API_TIMEZONE="+03:00"
      - GEOCODE_API_URL=http://api.openweathermap.org/geo/1.0
      - GEOCODE_API_DEFAULT_LIMIT=5
  
  app-todo:
    image: app-todo
    container_name: app-todo
    build:
      context: ./mvp3-app-todo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TODO_API_URL=http://localhost:5000
      - BRIDGE_API_URL=http://localhost:5001