version: "3"

services:
  todo-api:
    image: todo-api
    container_name: todo-api
    build:
      context: ./mvp3-api-todo
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=5000
    networks:
      - todo-network

  bridge-api:
    image: bridge-api
    container_name: bridge-api
    build:
      context: ./mvp3-api-bridge
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    networks:
      - todo-network

  todo-app:
    image: todo-app
    container_name: todo-app
    build:
      context: ./mvp3-app-todo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TODO_API_URL=http://todo-api:5000
      - BRIDGE_API_URL=http://bridge-api:5001
    depends_on:
      - todo-api
      - bridge-api
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
